{{- if not .Values.cloudscale.token.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudscale-token
type: Opaque
data:
  access-token: {{ required "cloudscale.token.value is required" .Values.cloudscale.token.value | b64enc | quote }}
{{- end }}
