---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csi-cloudscale.controller-service-account-name" . }}
  {{ include "csi-cloudscale.namespace-in-yaml-manifest" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csi-cloudscale.node-service-account-name" . }}
  {{ include "csi-cloudscale.namespace-in-yaml-manifest" . }}
