---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csi-cloudscale.controller-service-account-name" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csi-cloudscale.node-service-account-name" . }}
