---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-csi-cloudscale-controller-sa
  namespace: {{ .Release.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-csi-cloudscale-node-sa
  namespace: {{ .Release.namespace }}
